project_id = "hiyeumhhslcsrbtwcqyr"

[functions.coach-chat]
verify_jwt = false

[functions.coach-learn]
verify_jwt = true

[functions.generate-memory-image]
verify_jwt = false

[functions.generate-psychogram]
verify_jwt = true

[functions.log-token-usage]
verify_jwt = false

[functions.generate-memory-book]
verify_jwt = false

[functions.profile-assistant]
verify_jwt = false

[functions.resonanzradar-chat]
verify_jwt = false
